In [1]:
import numpy as np

In [4]:
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [6]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6]])
a2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
a3 = np.array([[[1,2,3],
                [4,5,6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [9]:
a2.ndim

2

In [10]:
a3.ndim

3

In [11]:
import pandas as pd

In [12]:
df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [14]:
one_ar = np.ones((10,2))

In [15]:
one_ar

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
zero_ar = np.zeros((7,2,3))

In [17]:
zero_ar

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [25]:
step_three = np.arange(0,101,3)
step_three

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [26]:
ran_ar = np.random.randint(0,10, size=(7,2))
ran_ar

array([[7, 3],
       [6, 1],
       [4, 0],
       [6, 1],
       [5, 9],
       [4, 0],
       [7, 0]])

In [27]:
ran_ar_f = np.random.rand(3,5)
ran_ar_f

array([[0.24199855, 0.57893385, 0.40962962, 0.13404392, 0.69868446],
       [0.15065835, 0.42189814, 0.86104117, 0.19794738, 0.10155732],
       [0.93353112, 0.88214319, 0.66538121, 0.57073724, 0.61786096]])

In [28]:
np.random.seed(42)

new_ran = np.random.randint(0,10, size=(4,6))
new_ran

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [29]:
unique_num = np.random.randint(1,10, size=(3,7))
unique_num

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [30]:
np.unique(unique_num)

array([1, 2, 3, 4, 5, 7, 9])

In [31]:
unique_num[0]

array([9, 1, 3, 7, 4, 9, 3])

In [32]:
unique_num[1]

array([5, 3, 7, 5, 9, 7, 2])

In [33]:
unique_num[:1]

array([[9, 1, 3, 7, 4, 9, 3]])

In [34]:
unique_num[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [36]:
unique_num[:2,:2]

array([[9, 1],
       [5, 3]])

In [37]:
ran_num = np.random.randint(0,10, size=(3,5))
new_ones = np.ones((3,5))
ran_num

array([[6, 7, 2, 0, 3],
       [1, 7, 3, 1, 5],
       [5, 9, 3, 5, 1]])

In [38]:
new_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.add(ran_num, new_ones)

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [41]:
one_ones = np.ones((3,5))

In [42]:
np.subtract(ran_num, one_ones)

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [43]:
np.multiply(ran_num, one_ones)

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [44]:
np.square(ran_num)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [45]:
np.mean(ran_num)

3.8666666666666667

In [46]:
np.max(ran_num), np.min(ran_num)

(9, 0)

In [47]:
np.std(ran_num)

2.578543947441829

In [48]:
np.var(ran_num)

6.648888888888889

In [49]:
ran_num.reshape(3,5,1)

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [50]:
ran_num.T

array([[6, 1, 5],
       [7, 7, 9],
       [2, 3, 3],
       [0, 1, 5],
       [3, 5, 1]])

In [52]:
first_arr = np.random.randint(0,10, size=(3,3))
second_arr = np.random.randint(0,10, size=(3,2))

In [53]:
np.dot(first_arr, second_arr)

array([[ 57,  49],
       [128, 135],
       [ 42,  68]])

In [55]:
first_arr = np.random.randint(0,10, size=(4,3))
second_arr = np.random.randint(0,10, size=(4,3))

In [56]:
np.dot(first_arr, second_arr.T)

array([[  7,  56,  28,  14],
       [ 14,  40,  36,  10],
       [ 69, 153, 111,  57],
       [ 62, 140, 100,  52]])

In [57]:
first_arr > second_arr

array([[False,  True,  True],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [58]:
first_arr > 7

array([[False, False, False],
       [False, False, False],
       [ True, False,  True],
       [ True, False,  True]])

In [59]:
np.sort(first_arr)

array([[0, 2, 7],
       [0, 2, 4],
       [6, 9, 9],
       [6, 8, 8]])

In [60]:
np.argsort(first_arr)

array([[0, 2, 1],
       [1, 0, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [62]:
first_arr

array([[0, 7, 2],
       [2, 0, 4],
       [9, 6, 9],
       [8, 6, 8]])

In [63]:
np.argmax(first_arr)

6

In [64]:
np.argmin(first_arr)

0

In [66]:
np.argmax(first_arr, axis=1)

array([1, 2, 0, 0])

In [67]:
np.argmin(first_arr, axis=0)

array([0, 1, 0])

In [70]:
np.random.normal(0.0, 2.0 , 10)

array([ 4.57445197,  3.245841  ,  1.64746615,  0.58611849,  1.79326077,
       -1.22064403, -0.63233179, -2.96484849, -0.45769503,  1.92528258])